import { NextApiRequest, NextApiResponse } from 'next';
import axios from 'axios';

const PESAPAL_URL = process.env.NODE_ENV === 'production' 
  ? 'https://pay.pesapal.com/v3' 
  : 'https://cybqa.pesapal.com/v3'; // Sandbox url

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'POST') return res.status(405).json({ message: 'Method not allowed' });

  const { amount, username } = req.body;

  try {
    // 1. Authenticate with PesaPal
    const authRes = await axios.post(`${PESAPAL_URL}/api/Auth/RequestToken`, {
      consumer_key: process.env.PesaPal_Consumer_Key,
      consumer_secret: process.env.PesaPal_Consumer_Secret,
    });

    const token = authRes.data.token;

    // 2. Register an IPN URL or get an existing IPN ID 
    // Note: For a true production flow, you'll want to save/cache your IPN ID.
    const ipnRes = await axios.post(
      `${PESAPAL_URL}/api/URLSetup/RegisterIPN`,
      {
        url: `${process.env.NEXT_PUBLIC_APP_URL || 'https://yourdomain.com'}/api/payments/pesapal-callback`,
        ipn_notification_type: 'GET',
      },
      { headers: { Authorization: `Bearer ${token}` } }
    );

    const ipnId = ipnRes.data.ipn_id;

    // 3. Generate a Unique Tracking ID (Merchant Reference)
    const reference = `TIP-${username?.toUpperCase()}-${Date.now()}`;

    // 4. Request the payment order URL
    const orderRes = await axios.post(
      `${PESAPAL_URL}/api/Transactions/SubmitOrderRequest`,
      {
        id: reference,
        currency: 'KES', // Or 'USD' depending on what your currency settings permit
        amount: parseFloat(amount),
        description: `Tip for @${username}`,
        callback_url: `${process.env.NEXT_PUBLIC_APP_URL || 'https://your.onlycrave.com'}/${username}/tip?success=true`,
        notification_id: ipnId,
        billing_address: {
          email_address: "onlycrave@mail.com", // Fallback info if not supplied
          phone_number: "0700000000",
          first_name: "Guest",
          last_name: "User",
        }
      },
      { headers: { Authorization: `Bearer ${token}` } }
    );

    // 5. Send back the redirect url generated by PesaPal
    if (orderRes.data && orderRes.data.redirect_url) {
      return res.status(200).json({ success: true, redirectUrl: orderRes.data.redirect_url });
    } else {
      throw new Error("Failed to generate order redirect link");
    }

  } catch (error: any) {
    console.error("PesaPal Error: ", error.response?.data || error.message);
    return res.status(500).json({ success: false, message: error.response?.data?.error?.message || "PesaPal initiation failed." });
  }
}
